---
title: "Exercices de révision"
output:
  pdf_document:
    toc: yes
    number_section: yes
  html_document:
    keep_md: yes
    number_section: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analyse
## Calcul de périodicité

Calculer la périodicité de la fonction $$f\colon x \mapsto \cos(5\pi t) + \sin (\frac{3}{2}\pi t)$$

## Factorisation $a^n -b^n$

Factoriser $a^n -b^n$ pour $n\in\mathbb N$

## Série harmonique et série harmonique alternée
Notons :

$$
H_n = \sum_{k=1}^n\frac{1}{k} ,
\quad
A_n = \sum_{k=1}^n\frac{(-1)^{k-1}}{k}
$$
Et :
$$
G_n = \sum_{k=1}^n\frac{1}{k^2},
\quad
B_n= \sum_{k=1}^n\frac{(-1)^{k}}{k^2}
$$

Montrer que :  

1. $\underset{n\to+\infty}{\lim} H_n = +\infty$ et $\underset{n\to+\infty}{\lim} A_n = \ln(2)$
2. Justifier la convergence de $G_n$ et $B_n$ et calculer $\underset{n\to+\infty}{\lim} B_n$ (sachant que $\sum_{k=1}^{+\infty}\frac{1}{k^2} = \frac{\pi^2}{6}$)

**Indications** :  

- Montrer que $H_{2n}-H_n \underset{n\to+\infty}\to \ln(2)$ 
- Décomposer les ordres pairs et impairs de $A_{2n}$, $\displaystyle P_{2n} = \sum_{\underset{k \text{ pair}}{k=1}}^{2n} \frac{(-1)^{k-1}}{k}$ et $\displaystyle I_{2n} = \sum_{\underset{k \text{ impair}}{k=1}}^{2n} \frac{(-1)^{k-1}}{k}$, pour montrer que $A_{2n} = H_{2n}-H_n$


## Calcul d'une intégrale

Justifier l'existence et calculer :
$$
\int_{0}^{+\infty} (x^2 +6x +3)\exp(-x)\mathrm{d}x
$$
(Réponse : -3)

## Exercices oraux

### Exercice 1

Soit ${(u_n)}_n$ une suite définie de la façon suivante :
$$
u_{n+1} = u_n + \frac{1}{n^\alpha u_n}\text{ avec }\alpha>0\text{ et } u_1>0
$$

1) Nature de la suite ${(u_n)}_n$

2) Trouver un équivalent de :  
  * $l - u_n$ quand $u_n$ converge vers $l$  
  
  * $u_n$ quand $u_n$ diverge
    

# Algèbre

## Espaces vectoriels

### Réunion de sev (18.10)

Soient $E$ un $\mathbb K-$ev, $A$, $B$ deux sev de $E$. Montrer que les deux propriétés suivantes sont équivalentes :

1. $A \cup B$ est un sev de $E$

2. $A \subset B$ ou $B \subset A$

### Inégalité sur des carrés de dimensions de sev (18.12)

Soient $E$ un $\mathbb K-$ev de dimension finie, $E, $F$ deux sev de $E$. Montrer :
$\geq$
$$
(\dim (F+G))^2 + (\dim (F\cap G))^2 \geq (\dim (F))^2 +(\dim (G))^2 
$$

## Exercices oraux

### Exercice oral improvisé

Soient $A$, $B\in \mathcal M_n(\mathbb R)$  orthogonales, $\alpha \in ]0,1[$. 

Montrer que si $\alpha A + (1-\alpha) B$ est orthogonale alors $A = B$

### Exercice oral improvisé

Soit $u \colon E \to E$ où $E$ est un espace vectoriel euclidien.

On suppose qu'il existe $\lambda>0$ et $\mu < 0$ deux valeurs propre de $u$.

Montrer qu'il existe $x\in E, \,x\ne 0$ tels que$\langle u(x) \mid x\rangle=0$



# Statistiques

## Exercice : calcul d'intégrales
Soient $a,b,c\in\mathbb R$ avec $a>0$. Montrer que 
$$
\int_{-\infty}^{+\infty} \exp(-ax^2+bx+c)\mathrm{d}x = \sqrt{\frac{\pi}{a}}\exp\left(\frac{b^2}{a} + c\right)
$$
Sachant que $\displaystyle\int_{-\infty}^{+\infty} \exp(-x^2)\mathrm{d}x = \sqrt{\pi}$

## Équivalences intégrales infinies

Soit $f$ une fontion $C^1$ sur $[0,+\infty[$, continue, positive, décroissante.
Montrer que : si $\int_0^{+\infty}f(x) \mathrm{d}x$ converge alors $\lim_{x\to+\infty}xf(x) = 0$


**Solution :**

Notons $F(x) = \int_0^x f(t)\mathrm{d}t$. On a :
$$\int_{x/2}^xf(t)\mathrm{d}t = F(x)-F(x/2)\geq \int_{x/2}^x f(x)\mathrm{d}t = \frac{xf(x)}{2} \geq 0$$
D'où le résultat voulu d'après le théorème des gendarmes

## Exercices oraux

### Exercice 1

Soient $a>0, \, r>0$. On dit que $T \sim \mathcal P(a,r)$ lorsque la densité de $T$ est :
$$
f_T(x) = \begin{cases}
\frac{ar^a}{(x+r)^{a+1}} &\text{ si }x>0 \\
0&\text{ si }x\leq 0
\end{cases}
$$
Soient $a,\, b,\, c$ trois réels strictements positifs et $A,\, B,\, C$ trois variables aléatoires indépendantes telles que $A\sim \mathcal P(a,r)$, $B\sim \mathcal P(b,r)$ et $C\sim \mathcal P(c,r)$.  
Notons $X=\min(B,\,C)$, $Y=\min(A,\,C)$ et $Z=\min(A,\,B)$

1. Trouver la loi de $X$, $Y$ et $Z$.  
2. Calculer $\mathbb P(X=Y)$  
3. Soit ${(U_n)}_n$ une suite de variables aléatoires telles que $U_n \sim \mathcal P\big(n,\frac{n}{\lambda}\big)$. Convergence en loi de ${(U_n)}_n$ ?